spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        package-to-scan: com.example.cadastrousuario.fakeapius.infrastructure.entities
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8282